### ISSUE TITLE
[Bug, sim] When predicting volume with RelDiff, residual errors are always > 0 (wonky)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1270]
### The bug

When predicting RelDiff volume, residual errors are always > 0 (wonky).

Pre-requisite: Bug [#1271](https://github.com/oceanprotocol/pdr-backend/issues/1271) "SimEngine._sell() 'Out of tokens, this shouldn't happen' when predicting on Volume"
- The bug ^ is show-stopping: we can't even do sim runs on Volume until ^ is solved
- The issue of _this_ bug was observed on Jun 19. The bug ^ was introduced in evening Jun 20.

### Key setup params:

```yaml
predictoor_ss:
  predict_train_feedsets:
    - predict: binance BTC/USDT v 5m
      train_on:
      - binance BTC/USDT v 5m

predictoor_ss:
  aimodel_ss: # used by AimodelFactory
    approach: ClassifLinearRidge

  aimodel_data_ss: # used by AimodelDataFactory
    transform: RelDiff # None -> raw value of signal; RelDiff -> rel % diff
 ```

[ppss.yaml.txt](https://github.com/user-attachments/files/15924571/ppss.yaml.txt)
