### ISSUE TITLE
[Sim] Skipped Multisim Values at 50k Iterations

### ISSUE THREAD

**Issue by graceful-coder** [oceanprotocol/pdr-backend#1582]
### Describe the bug
The `ClassifLinearLasso` & `ClassifLinearElasticNet` models are skipping over `run_number = 0` the first multisim run at 50k iterations, regardless of their calibration. However, `ClassifLinearLasso_Balanced` & `ClassifLinearElasticNet_Balanced` models are unaffected.

When `my_ppss.yaml` params are set to:

```
multisim_ss:
  approach: SimpleSweep # SimpleSweep | FastSweep (future) | ..
  sweep_params:
  - trader_ss.buy_amt: 1000 USD
  - predictoor_ss.aimodel_data_ss.max_n_train: 1000, 2000, 5000
  - predictoor_ss.aimodel_data_ss.autoregressive_n: 1, 2
```

The models are skipping over the first multisim run with `max_n_train = 1000` and `autoregressive_n = 1` but complete the rest of the multisim flow. This issue is reproduced in simulations with all three calibrations (Sigmoid, Isotonic, and None) at 50k iterations. However, this issue is not occurring at 5k iterations.

### To Reproduce

1. Attached is the `my_ppss.yaml` file which failed
2. Run the pdr multisim with the attached `my_ppss.yaml` file
[my_ppss_yaml.txt](https://github.com/user-attachments/files/16871684/my_ppss_yaml.txt)
