### ISSUE TITLE
[EPIC] Make $ trading across 500+ tokens; 5m; trade rarely per token. Sim, and live

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1712]
### Background / motivation

Make $ trading on 5m, a timescale good enough for agent evolution. (And more fun in general:)

How: Trade across 500+ tokens and trade rarely per token. Eg only 1-3 trades every 5m. Aka "snipe". Few relative trades → low fees. 

### TODOs / DoD

- [ ] Revive pdr-backend sim, on 5m, btc, binance. Backend/cli, sim, and new dashboard too.
- [ ] Simplify pdr-backend codebase for my goals here: chop things I won't use. Eg ETL.
- [ ] Update trader bot: 
  - [ ] trade across >>1 tokens at once. Don't _have_ to trade any token at any given epoch. Using _existing_ supported tokens (top 10). 
  - [ ] Includes: heavily modify analytics
  - [ ] Includes: keep take profit / stop loss 
- [ ] Reframe models to:  'will price go up *anytime* in next 5 min?'. That is: "If prediction says 'price goes up > 0.2% anytime in the next 5 min', then buy; and as soon as actual price > 0.2% above, then sell. And, vice versa for going down. And, if still in position at 5min mark, then exit position".
- [ ] Support top 10 tokens --> top 500 tokens. Historical data can be short. (Support enough for my purposes, not generally for pdr)

### Appendix: things to add, only if we need, to make $

- trade on cowswap only when fee=zero thanks to coincidence-of-wants.  Starting point is pdr-backend; maybe add non-stationary fix or other Udit tricks.
- Udit's non-stationary trick. Though we can probably get aware with short-term data & models, given so many tokens. (And it'd be very expensive to do longer-term anyway.)
- Ref: [make $ trading](https://docs.google.com/document/d/1xmhdHzjQBLs-kUp6PIfw1LcNXtLddO2GnRUHTF1SAKU/edit?tab=t.0#heading=h.xv57656hlpyi) GDoc. A bit dated, but many great ideas.
- Ref: [5m trading ideas](https://docs.google.com/document/d/1F5QSiaV3euf0-5q-48BHvaOqKVui0uJs751SmtQ8q7k/edit?tab=t.0#heading=h.qxwpujkl7sw4) in 1e 9 GDoc

**Comment by trentmc** [comment]
On baseline modeling req'ts. Jan 26, 2025

### Hypothesis: "without the following model req'ts, model has no hope":

- use price quantiles, not raw values (Udit trick)
- at least weakly nonlinear (FFX)
- reliable confidence calc --> critical for choosing when to trade
- bound amount traded, using confidence calc
- bound amount made & lost (reduce variance) -> take profit / stop loss

If I can make $ without needing all of these, this hyp is wrong

## Update 8:40: I'm making money! Convergence curve is excellent.  _Without_ the req'ts above! 

Biggest factors: very small SL/TP thr, and much larger autoregressive_n. Reasoning behind each param is below.

Convergence curve:
![Image](https://github.com/user-attachments/assets/06952c13-681d-4c22-8823-ca7e51afaf13)

All key params:
```
    max_n_train: 5700 # 20d. "Short enough to not get killed by nonstationarity. Long enough for a non-shitty lin model"
    autoregressive_n: 12 # 1h. Enough to "spot a pattern", vs eg 2 where no chance
..    
  aimodel_ss:
    approach: ClassifLinearRidge # Stable, don't harshly filter any prev param
    weight_recent: 10x_5x # "Bias most recent samples"
    balance_classes: None # "KISS" (maybe balancing helps more thogh)
    calibrate_probs: CalibratedClassifierCV_Sigmoid # "best possible confidence calc"
    train_every_n_epochs: 1 # "don't scrimp on model-building compute, let's have the best models for params above"
..

trader_ss:
..
    fee_percent: 0.0 # set to zero now to see if any chance at all making $. If success, then set to >0
    confidence_threshold: 0.75 # "snipe"
    stop_loss_percent: 0.001 # 0.1%. Reduce variance, don't let 1 trade kill us
    take_profit_percent: 0.001 # 0.1%. Reduce variance, take our win and move on
```

**Comment by trentmc** [comment]
### Update 8:40: I'm making money; convergence curve is excellent;  _without_ the req'ts above

Biggest factors: very small SL/TP thr, and much larger autoregressive_n. Reasoning behind each param is below.

Convergence curve:
![Image](https://github.com/user-attachments/assets/9afdba2f-6245-43c0-a4dc-6e98080a506d)

All key params:
```
    max_n_train: 5700 # 20d. "Short enough to not get killed by nonstationarity. Long enough for a non-shitty lin model"
    autoregressive_n: 12 # 1h. Enough to "spot a pattern", vs eg 2 where no chance
..    
  aimodel_ss:
    approach: ClassifLinearRidge # Stable, don't harshly filter any prev param
    weight_recent: 10x_5x # "Bias most recent samples"
    balance_classes: None # "KISS" (maybe balancing helps more thogh)
    calibrate_probs: CalibratedClassifierCV_Sigmoid # "best possible confidence calc"
    train_every_n_epochs: 1 # "don't scrimp on model-building compute, let's have the best models for params above"
..

trader_ss:
..
    fee_percent: 0.0 # set to zero now to see if any chance at all making $. If success, then set to >0
    confidence_threshold: 0.75 # "snipe"
    stop_loss_percent: 0.001 # 0.1%. Reduce variance, don't let 1 trade kill us
    take_profit_percent: 0.001 # 0.1%. Reduce variance, take our win and move on
```
