### ISSUE TITLE
[YAML] Avoid NETWORK_OVERRIDE while supporting remote barge, or make it more maintainable

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#499]
Parent: [EPIC: YAML] Add YAML & CLI. "v0.2" of Predictoor [#400](https://github.com/oceanprotocol/pdr-backend/issues/400)

### Background / motivation

In YAML-CLI2 branch, in [ppss.yaml](https://github.com/oceanprotocol/pdr-backend/blob/yaml-cli2/ppss.yaml) file, in section web3_pp, one specifies parameters for different networks like "sapphire-mainnet" or "sapphire-testnet". An example:
```
  sapphire-testnet:
    address_file: "~/.ocean/ocean-contracts/artifacts/address.json"
    rpc_url: https://testnet.sapphire.oasis.dev
    subgraph_url: https://v4.subgraph.sapphire-testnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph
    owner_addrs: "0xe02a421dfc549336d47efee85699bd0a3da7d6ff" # OPF deployer address
```

For using the ganache / barge testnet, at first there was just one option: "development". Its RPC URL is a local url: `http://localhost:8545`. Details:
```
  development:
    address_file: "~/.ocean/ocean-contracts/artifacts/address.json"
    rpc_url: http://localhost:8545
    subgraph_url: http://localhost:9000/subgraphs/name/oceanprotocol/ocean-subgraph
    owner_addrs: "0xe2DD09d719Da89e5a3D0F2549c7E24566e947260" # OPF deployer address
```

This works fine for anyone who can run ganache / barge _locally_. And it works fine for remote CI. Alas, since barge uses Docker, and MacOS plays badly with Docker, it means anyone using MacOS cannot run barge locally. That includes me (Trent). 

My (Trent's) workaround is: run barge in an Azure Virtual Private Server (VPS), and in ppss.yaml have a _second_ network specification that points to the url of this network "barge-pytest". 
```
  barge-pytest:
    address_file: "~/barge-pytest.address.json"
    private_key: "0xc594c6e5def4bab63ac29eed19a134c130388f74f019bc74b8f4389df2837a58"
    rpc_url: http://74.234.16.165:8545
    subgraph_url: http://74.234.16.165:9000/subgraphs/name/oceanprotocol/ocean-subgraph
    owner_addrs: "0xe2DD09d719Da89e5a3D0F2549c7E24566e947260" # OPF deployer address. Taken from ocean.py setup-local.md FACTORY_DEPLOYER_PRIVATE_KEY
```

The "barge-pytest" VPS version of barge has no extra bots running. I also have another VPS version of barge called "barge-predictoor-bot", which runs all bots except predictoor bot; it's useful for testing predictoor bots.

This is very clean from perspective of the CLI, because in each CLI command one specifies the network as an argument. Great!

I have a nice README showing how to use both VPS barges. I use this README as my main flow as I'm developing in yaml-cli2. https://github.com/oceanprotocol/pdr-backend/blob/main/READMEs/vps.md

But there's a hitch when running unit tests, locally or on remote CI. The hitch is: all unit tests are currently configured to use "development" network, ie local barge. So my workaround for that was to create "NETWORK_OVERRIDE" envvar. If NETWORK_OVERRIDE is detected by web3_pp, then it sets the network to the value of the envvar, rather than the value specified by web3_pp's constructor.

In general we don't want envvars except PRIVATE_KEY. So NETWORK_OVERRIDE should normally _not_ be set; just by me (Trent) or anyone wanting to use barge-pytest. 

There were 10-15 unit tests where I needed to un-set the NETWORK_OVERRIDE for that envvar. Sloppier than I would like, but workable. It also gets annoying: in the brief time I've had this override setup, when others make changes that affect the override, I have to go and make fixes myself locally.

### Goal of this issue

Avoid NETWORK_OVERRIDE while supporting remote barge, or make it more maintainable.

How? Either:
- (a) If possible: find a way to avoid need for NETWORK_OVERRIDE when using barge from Azure, or
- (b) In unit tests, _also_ test for NETWORK_OVERRIDE using barge. Therefore when changes _do_ happen, then NETWORK_OVERRIDE continues to get supported without Trent having to keep chasing to fix his stuff locally
