### ISSUE TITLE
[CLI] "pdr predictoor" asks for an approach, but it's already specified in yaml

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#930]
**Describe the bug**

In CLI interface:
```text
Main tools:
  ...
  pdr predictoor APPROACH PPSS_FILE NETWORK
  ...
```

Note how one is supposed to specify `APPROACH` for the predictoor bot.

But in ppss.yaml:
```yaml
predictoor_ss:
...
  approach: 2 # 1->50/50; 2->two-sided model-based; 3-> one-sided model-based
  stake_amount: ...
```

Therefore the CLI is redundant.

### TODO

- [ ] Remove need for `APPROACH` in CLI. Update tests etc as needed
